services:
  portfolio:
    build: .
    restart: unless-stopped
    env_file: .env
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`enkay.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"